package ru.darkcat.camera.crypto;

import java.security.GeneralSecurityException;
import java.util.Arrays;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * Small, Android-free AES-GCM envelope used by {@link SecureCredentialStore}.
 *
 * <p>The serialized layout intentionally remains {@code IV || ciphertext || tag}, with the
 * historical 12-byte IV, so credentials written by older DarkCat builds remain readable. The
 * encryption IV is always generated by the crypto provider. This is required for Android
 * Keystore keys whose randomized-encryption policy rejects caller-provided IVs.</p>
 */
public final class CredentialCipher {
    static final int IV_LENGTH = 12;
    private static final int TAG_LENGTH_BITS = 128;
    private static final int TAG_LENGTH_BYTES = TAG_LENGTH_BITS / 8;

    public static byte[] encrypt(SecretKey key, byte[] plaintext) throws GeneralSecurityException {
        return encrypt(key, plaintext, Cipher.getInstance("AES/GCM/NoPadding"));
    }

    static byte[] encrypt(SecretKey key, byte[] plaintext, Cipher cipher) throws GeneralSecurityException {
        // Do not pass an IV here. Android Keystore must generate it for randomized AES-GCM keys.
        cipher.init(Cipher.ENCRYPT_MODE, key);
        byte[] iv = cipher.getIV();
        if (iv == null || iv.length != IV_LENGTH) {
            throw new GeneralSecurityException("AES-GCM provider returned an unsupported IV");
        }
        byte[] ciphertext = cipher.doFinal(plaintext == null ? new byte[0] : plaintext);
        byte[] envelope = new byte[iv.length + ciphertext.length];
        System.arraycopy(iv, 0, envelope, 0, iv.length);
        System.arraycopy(ciphertext, 0, envelope, iv.length, ciphertext.length);
        return envelope;
    }

    public static byte[] decrypt(SecretKey key, byte[] envelope) throws GeneralSecurityException {
        if (envelope == null || envelope.length < IV_LENGTH + TAG_LENGTH_BYTES) {
            throw new GeneralSecurityException("Truncated AES-GCM credential envelope");
        }
        byte[] iv = Arrays.copyOfRange(envelope, 0, IV_LENGTH);
        byte[] ciphertext = Arrays.copyOfRange(envelope, IV_LENGTH, envelope.length);
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(TAG_LENGTH_BITS, iv));
        return cipher.doFinal(ciphertext);
    }

    private CredentialCipher() { }
}
